stages:
  - build
  - test

build api:
  stage: build
  tags:
    - first-runner
  image: docker:29
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker buildx build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --cache-from=$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --push . --target=deploy
    - docker buildx build -t $CI_REGISTRY_IMAGE:test-$CI_COMMIT_REF_SLUG --cache-from=$CI_REGISTRY_IMAGE:test-$CI_COMMIT_REF_SLUG --push . --target=test

  rules:
    - changes:
      - Dockerfile
      - main.py
      - requirements.txt
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH 

test api:
  stage: test
  tags:
    - first-runner
  image: $CI_REGISTRY_IMAGE:test-$CI_COMMIT_BRANCH
  # gitlab coverage report: https://docs.gitlab.com/ci/testing/code_coverage/
  script:
    - pytest --cov
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
