stages:
  - build
  - test
default:
  tags:
    - lab-vm

build api:
  stage: build
  image: docker:29
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - if test $CI_COMMIT_BRANCH = $CI_DEFAULT_BRANCH; then REGISTRY_TAG=latest; else REGISTRY_TAG=$CI_COMMIT_BRANCH; fi
    - docker buildx build -t $CI_REGISTRY_IMAGE:$REGISTRY_TAG --cache-from=$CI_REGISTRY_IMAGE:$REGISTRY_TAG --push . --target=deploy
    - docker buildx build -t $CI_REGISTRY_IMAGE:test-$REGISTRY_TAG --cache-from=test-$CI_REGISTRY_IMAGE:$REGISTRY_TAG --push . --target=test
  rules:
    - changes:
      - Dockerfile
      - "main.py"
      - requirements.txt
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH 

test api:
  stage: test
  image: $CI_REGISTRY_IMAGE:test-$CI_COMMIT_BRANCH
  # gitlab coverage report: https://docs.gitlab.com/ci/testing/code_coverage/
  script:
    - pytest --cov
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
