services:
  api:
    image: ${CI_REGISTRY_IMAGE}:${IMAGE_TAG}
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${STACK_NAME}.rule=Host(`${STACK_NAME}.doe25.swarm.chas-lab.dev`)"
        - "traefik.http.routers.${STACK_NAME}.entrypoints=https"
        - "traefik.http.routers.${STACK_NAME}.tls=true"
        - "traefik.http.routers.${STACK_NAME}.tls.certresolver=le"
        - "traefik.http.services.${STACK_NAME}.loadbalancer.server.port=8000"

networks:
  traefik-public:
    external: true
    name: "u2vny23362londw734lqofhvz"  # Detta är din "räddare i nöden" mot felmeddelandet